# Generated by Django 5.0.2 on 2024-09-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('devices', '0001_initial'), ('devices', '0002_device_params'), ('devices', '0003_device_value'), ('devices', '0004_alter_device_params'), ('devices', '0005_alter_device_params'), ('devices', '0006_rename_value_device_default_value_and_more'), ('devices', '0007_alter_device_max_value_alter_device_min_value'), ('devices', '0008_remove_device_default_value_remove_device_max_value_and_more'), ('devices', '0009_relayperiodicday_relayperiodicperiod'), ('devices', '0010_device_type'), ('devices', '0011_alter_device_type'), ('devices', '0012_alter_device_type'), ('devices', '0013_relayperiodicmanualactivation')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.location')),
                ('config_file', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('relay', 'Relay'), ('relay-periodic', 'Periodic relay')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RelayPeriodicDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='RelayPeriodicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='RelayPeriodicManualActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
