# Generated by Django 5.0.2 on 2024-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='params',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
