# Generated by Django 5.0.2 on 2024-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
