# Generated by Django 5.0.2 on 2024-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='params',
            field=models.CharField(default='', max_length=200),
        ),
    ]
