# Generated by Django 5.0.2 on 2024-03-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='params',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
