# Generated by Django 5.0.2 on 2024-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='value',
            new_name='default_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='params',
        ),
        migrations.AddField(
            model_name='device',
            name='config_file',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='max_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='min_value',
            field=models.IntegerField(null=True),
        ),
    ]
