# Generated by Django 5.0.2 on 2024-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_max_value_alter_device_min_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
    ]
