# Generated by Django 5.0.2 on 2024-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('switch', 'Switch'), ('relay-periodic', 'Periodic relay')], max_length=20),
        ),
    ]
