# Generated by Django 5.0.2 on 2024-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('relay', 'Relay'), ('relay-periodic', 'Periodic relay')], max_length=20),
        ),
    ]
